extends: airbnb-base
env:
  es6: true
  node: true
plugins: ['prettier']
parserOptions:
  # ecmaVersion: 8
  sourceType: module
globals:
  _: false
  sails: false
  Axios: false
  capitalize: false
  moment: false
  Paystack: false
  FirebaseAdmin: false
  crypto: false
  Raven: false
  responseHelper: false
  #Services
  jwtService: false
  DistanceService: false
  PricingService: false
  NotificationService: false
  #Models
  User: false
  Card: false
  BankAccount: false
  Ride: false
  Delivery: false
  Driver: false
  Location: false
  Device: false
  Task: false
  Transaction: false
  Wallet: false
  Vehicle: false
rules:
  max-len:
    - 0
    - 200
    - 2
  no-console: error
  no-underscore-dangle: off
  comma-dangle: [error, always-multiline, { functions: never }]
  func-names: off
  camelcase: off
  consistent-return: off
  global-require: off
  arrow-parens: off
  object-curly-newline: off
  nonblock-statement-body-position: off
  curly: off
